api_platform:
  title: BileMo Api
  version: 1.0.0
  formats:
    jsonld: ["application/ld+json"]
  docs_formats:
    jsonld: ["application/ld+json"]
    jsonopenapi: ["application/vnd.openapi+json"]
    html: ["text/html"]
  defaults:
    stateless: true
    pagination_partial: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
      max_age: 0
      shared_max_age: 3600
      invalidation:
        xkey:
          glue: ", "
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
  keep_legacy_inflector: false
  use_symfony_listeners: true
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
